--- #YAML:1.0
name:               WWW-PDB
version:            0.00_01
abstract:           Perl interface to the Protein Data Bank
author:
    - Miorel-Lucian Palii <mlpalii@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Fcntl:                0
    File::Path:           1.08
    File::Spec:           3.12
    IO::File:             1.13
    IO::Uncompress::Gunzip:  2.015
    Net::FTP:             2.77
    SOAP::Lite:           0.710.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
